name: Execute Load And Spike Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Build image
        run: docker build -t cy .

      - name: Run API tests
        run: docker run cy --record false --env TAG=@api-feature

      - name: Run Chrome tests
        run: docker run cy -- --record false --browser chrome --env TAG=@browser-feature

      - name: Run Firefox tests
        run: docker run cy -- --record false --browser firefox --env TAG=@browser-feature