name: Execute Load And Spike Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Build image
        run: docker build -t cy .

      - name: Run API tests
        run: docker run cy

      - name: Run Chrome tests
        run: docker run cy -- --browser chrome

      - name: Run Firefox tests
        run: docker run cy -- --browser firefox