name: Execute Load And Spike Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Build image
        run: docker build -t cy .

      - name: Run API tests
        run: docker run cy --config videoRecording=false --env TAGS=@api-feature

      - name: Run Chrome tests
        run: docker run cy -- --config videoRecording=false --browser chrome --env TAGS=@browser-feature

      - name: Run Firefox tests
        run: docker run cy -- --config videoRecording=false --browser firefox --env TAGS=@browser-feature