name: Execute Load And Spike Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Run API tests
        run: docker run -v $PWD:/e2e -w /e2e cypress/included:latest